DROP TABLE IF EXISTS [dbo].["UUSKLIST"]; 
go
CREATE TABLE [dbo].["UUSKLIST"]
(
            PNR CHAR(13),
            GPNR CHAR(13),
            EFTERNAMN VARCHAR(255),
            FORNAMN VARCHAR(255),
            INLDATUM_PERS CHAR(10),
            COADRESS VARCHAR(4096),
            GATUADRESS VARCHAR(4096),
            POSTNR VARCHAR(4096),
            ORT VARCHAR(4096),
            LAND VARCHAR(4096),
            INLDATUM_ADRESS CHAR(10),
            TELNR VARCHAR(255),
            INLDATUM_TELNR CHAR(10),
            EPOSTADRESS VARCHAR(255),
            UPPEH VARCHAR(7),
            KURS CHAR(20),
            INST CHAR(4),
            POANG VARCHAR(5),
            KT VARCHAR(3),
            UF CHAR(3),
            KORT CHAR(4),
            FIN CHAR(3),
            PROGR VARCHAR(20),
            AKT VARCHAR(3),
            TERMIN VARCHAR(5),
            PTAKT VARCHAR(5),
            KAR   CHAR(3),
            TYP   CHAR(3),
            PLG   VARCHAR(255)
			 
)
go
ALTER TABLE ["UUSKLIST"] ADD AVLIDEN varchar(1); 
go
ALTER TABLE ["UUSKLIST"] ADD PROGRAMAVBROTT varchar(10); 
go

ALTER TABLE ["UUSKLIST"] ADD SKAPAD [datetime] NULL
go
ALTER TABLE ["UUSKLIST"] ADD UPPDATERAD [datetime] NULL 
go

DROP VIEW IF EXISTS [dbo].[viewUsmrSelectAll]; 
go
CREATE view viewUsmrSelectAll AS
select PNR,GPNR,EFTERNAMN,FORNAMN,INLDATUM_PERS, COADRESS, GATUADRESS,POSTNR,ORT,LAND,INLDATUM_ADRESS,TELNR,
INLDATUM_TELNR, EPOSTADRESS, UPPEH,KURS,INST,POANG,KT,UF,KORT,FIN,PROGR,AKT,TERMIN,PTAKT,KAR,TYP,PLG,SKAPAD,UPPDATERAD from ["UUSKLIST"]

